name: Generate Contribution Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # Allows manually running the job
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate the snake animation with custom colors
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ErascusPlatypus
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#B266FF&color_dots=#050012,#a8e6a2,#6cc24a,#43a047,#2e7d32
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#B266FF&color_dots=#050012,#a8e6a2,#6cc24a,#43a047,#2e7d32
          
      # Push generated files to the output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
