name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: ErascusPlatypus
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push generated files
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist
